name: Github Actions for Devops with python
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.9
    - name: Install dependencies
      run: |
        make install
    - name: format code
      run: |
        make format
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: ${{secrets.AWS_IAM_ROLE}}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: fastapi-wiki
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
